sudo: false
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

services: docker

env:
  global:
    - secure: Nbw4Kg8lsB/iwPb3Wruhli34OUADFvlwwQcv7AzWuYDg2K1qzRgRqNmC6THdXOdFp9rs8tnaru6lNkhoEsANeGjyl1qN37jyvnjTZdL71BakenNvWyvVGzAuYEQhpHEpDLcV1YrjRiPUAtd1PqVTOysjZWZhOHz7ybW5fe06zuo=
  jobs:
    - CHEF_LICENSE=accept

branches:
  only:
    - master

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef gem install knife-cookbook-doc
  - chef --version
  - cookstyle --version
  - foodcritic --version

script:
  - chef exec rake

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ac340e4acdb6_key -iv $encrypted_ac340e4acdb6_iv -in supermarket.pem.enc -out supermarket.pem -d
  - chef gem install stove
  - git config --global user.email "cookbooks@schubergphilis.com"
  - git config --global user.name "SBP Cookbooks CI"
  - git remote rm origin
  - git remote add origin https://sbp-cookbooks-ci:$GH_TOKEN@github.com/sbp-cookbooks/sbp_mcafee.git

deploy:
  - provider: script
    skip_cleanup: true
    script: STOVE_CONFIG=.stove chef exec stove
    on:
      repo: sbp-cookbooks/sbp_mcafee
      branch: master
      condition: "$(git diff @~1 metadata.rb | grep +version)"
